server:
  port: 8081

spring:
  application:
    name: usuarios-service

  datasource:
    url: jdbc:postgresql://localhost:5432/usuarios_db
    username: postgres # <- Tu usuario
    password: password # <- Tu contraseña
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"