server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/edge.p12
    key-store-password: password
    key-alias: localhost

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Candidatos-demo

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: candidatos_service_route
          uri: lb://MS-CANDIDATOS
          predicates:
            - Path=/ms-candidatos/**
          filters:
            - StripPrefix=1
        
        - id: usuarios_service_route
          uri: lb://USUARIOS-SERVICE
          predicates:
            - Path=/ms-usuarios/**
          filters:
            - StripPrefix=1

        - id: notificaciones_service_route
          uri: lb://MS-NOTIFICACIONES
          predicates:
            - Path=/ms-notificaciones/**
          filters:
            - StripPrefix=1

        - id: resultados_service_route
          uri: lb://MS-RESULTADOS
          predicates:
            - Path=/ms-resultados/**
          filters:
            - StripPrefix=1

app:
  eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "health,info"

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG