spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  cloud:
    stream:
      enabled: false
    function:
      definition: 
  h2:
    console:
      enabled: true
  autoconfigure:
    exclude:
      - org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration
      - org.springframework.cloud.stream.config.BindingServiceConfiguration
      - org.springframework.cloud.stream.binding.BindingsHealthContributorAutoConfiguration

eureka:
  client:
    enabled: false

server:
  port: 8888
