spring:
  application:
    name: AUDITORIA-REGISTROS-SERVICE

  cloud:
    config:
      # Local
      #uri: http://localhost:8888
      # Para Docker
      uri: http://config-server:8888
      fail-fast: true
      retry:
        initial-interval: 3000
        multiplier: 1.3
        max-interval: 10000
        max-attempts: 20
      username: ${CONFIG_SERVER_USR:config-usr}
      password: ${CONFIG_SERVER_PWD:Config2025!}

  config:
    # Importa Config Server y luego tu openapi local
    import: "configserver:http://config-server:8888,optional:classpath:application-openapi.yaml"

# Banner opcional
banner:
  location: classpath:banner-local.txt