server.port=8082

spring.application.name=votaciones-service

spring.datasource.url=jdbc:postgresql://localhost:5433/votaciones_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.cloud.stream.function.definition=enviarNotificacionVotacion
spring.cloud.stream.bindings.enviarNotificacionVotacion-out-0.destination=topic-notificaciones
spring.cloud.stream.bindings.enviarVotacionAResultados-out-0.destination=topic-votaciones
spring.cloud.stream.kafka.binder.brokers=${SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS:localhost:9092}

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://host.docker.internal:8090/realms/votaciones/protocol/openid-connect/certs}

app.auditoria.base-url=http://AUDITORIA-REGISTROS-SERVICE

management.endpoints.web.exposure.include=*

logging.level.org.springframework.security=DEBUG