server:
  port: 8083 # Un nuevo puerto

spring:
  application:
    name: notificaciones-service
  
  # =======================================================
  # CONFIGURACIÓN DE SPRING CLOUD STREAM (KAFKA)
  # =======================================================
  cloud:
    stream:
      # Le decimos que vamos a usar Kafka
      default-binder: kafka
      
      bindings:
        # Define una "entrada" de mensajes.
        # El nombre 'procesarNotificacion-in-0' se compone de:
        # [nombreDeLaFuncion]-[in/out]-[indice]
        procesarNotificacion-in-0:
          # El "topic" de Kafka que vamos a escuchar
          destination: topic-notificaciones
          # El grupo de consumidores (permite escalar el servicio)
          group: notificaciones-group

      # Configuración del conector de Kafka
      kafka:
        binder:
          # La dirección del servidor de Kafka. Usaremos el nombre de servicio de Docker.
          brokers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8861/eureka
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: "*"