server:
  port: 8083

spring:
  application:
    name: notificaciones-service

  cloud:
    function:
      # Activamos las DOS funciones del servicio
      definition: procesarNotificacion;recibirEventoCandidatos

    stream:
      default-binder: kafka

      bindings:
        # 1) Consumer para correos (NotificacionDto) desde topic-notificaciones
        procesarNotificacion-in-0:
          destination: topic-notificaciones
          group: notificaciones-email-group
          content-type: application/json

        # 2) Consumer para eventos de candidatos desde 'notificaciones'
        recibirEventoCandidatos-in-0:
          destination: notificaciones
          group: notificaciones-candidatos-group
          content-type: application/json

      kafka:
        binder:
          # En Docker este host existe; si quieres usar localhost en local,
          # puedes sobreescribir con una env var, pero para ahora déjalo así.
          brokers: ${SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS:localhost:9092}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    com.votaciones: DEBUG